apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: reviews 
  name: reviews-pvc-volume
  namespace: demo-tinfo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: reviews-storage
  volumeMode: Filesystem
