apiVersion: v1
kind: Service
metadata:
  name: springboot-reviews-service
  namespace: demo-tinfo
  labels:
    app: springboot-reviews
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30140
    protocol: TCP
    name: http
  selector:
    app: springboot-reviews
